In [1]:
import numpy as np
import pandas as pd

In [2]:
movie = pd.read_csv('Movie.csv')
movie

,url,title,on_streaming_date,genre,runtime,certification,rating,tagline,overview,Director,...,Original Language,Budget,Revenue,keyword,Original Title,Writer,Author,Story,Teleplay,Characters
0,https://www.themoviedb.org//movie/112755,Evelyn,10/07/2012 (ES),"Thriller, Drama",1h 30m,NaN,64.0,NaN,Evelyn travels to Spain from his native villag...,Isabel de Ocampo,...,Spanish; Castilian,-,-,woman director,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.themoviedb.org//movie/482811,The Travel Agent,06/25/2015 (ES),Documentary,1h 29m,NaN,43.0,NaN,"Havana, Cuba, 54th year of US embargo. After h...",Niccolò Bruna,...,Spanish; Castilian,-,-,NaN,Pequeñas mentiras piadosas,NaN,NaN,NaN,NaN,NaN
2,https://www.themoviedb.org//movie/901379,1000 : Une autre histoire de la F1,08/19/2020 (FR),Documentary,NaN,NaN,100.0,NaN,We don't have an overview translated in Englis...,NaN,...,French,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.themoviedb.org//movie/327939,Fortunes,12/19/2008 (FR),Comedy,NaN,NaN,75.0,NaN,We don't have an overview translated in Englis...,Stéphane Meunier,...,French,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.themoviedb.org//movie/78258,Venus & Fleur,06/23/2004 (FR),Drama,1h 16m,NaN,48.0,"Young, Wild and Free","Fleur, a shy young Parisian in Marseilles, mee...",Emmanuel Mouret,...,French,-,-,NaN,Vénus et Fleur,Emmanuel Mouret,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39171,https://www.themoviedb.org//movie/504054,Stars by the Pound,07/17/2019 (FR),"Drama, Comedy",1h 28m,12,61.0,NaN,"Lois, 16, has only one dream: becoming an astr...",Marie-Sophie Chambon,...,French,-,-,NaN,100 kilos d'étoiles,Anaïs Carpita,NaN,NaN,NaN,NaN
39172,https://www.themoviedb.org//movie/674170,Muerte Salvaje,01/01/2014 (MX),NaN,1h 30m,NaN,50.0,NaN,A solitary rancher rides out of the desert pla...,NaN,...,Spanish; Castilian,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39173,https://www.themoviedb.org//movie/13098,Paid in Full,10/25/2002 (US),"Action, Crime, Drama",1h 38m,MA15+,68.0,The American Dream... Their way.,Ace is an impressionable young man working for...,Charles Stone III,...,English,-,"$3,090,862.00","new york city,street gang,drug trafficking,ghe...",NaN,NaN,NaN,NaN,NaN,NaN
39174,https://www.themoviedb.org//movie/830991,Ride the Eagle,07/30/2021 (US),"Comedy, Drama",1h 29m,NR,65.0,Change is in the air.,"When Leif’s estranged mother, Honey dies she l...",Trent O'Donnell,...,English,-,-,"yosemite,inheritance,death of mother,rekindled...",NaN,NaN,NaN,NaN,NaN,NaN
39175,https://www.themoviedb.org//movie/633929,You Will Remember Me,11/04/2022 (CA),Drama,1h 48m,NaN,60.0,A story told. A life relived.,A retired public figure and history professor ...,Éric Tessier,...,French,-,-,NaN,Tu te souviendras de moi,NaN,NaN,NaN,NaN,NaN

In [3]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39176 entries, 0 to 39175
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   url                39176 non-null  object
 1   title              39176 non-null  object
 2   on_streaming_date  39176 non-null  object
 3   genre              35843 non-null  object
 4   runtime            33251 non-null  object
 5   certification      18829 non-null  object
 6   rating             39176 non-null  float64
 7   tagline            12749 non-null  object
 8   overview           39174 non-null  object
 9   Director           37102 non-null  object
 10  Screenplay         8607 non-null   object
 11  cast1              33821 non-null  object
 12  cast1_link         33821 non-null  object
 13  cast2              31752 non-null  object
 14  cast2_link         31752 non-null  object
 15  cast3              30139 non-null  object
 16  cast3_link         30139 non-null  object
 17  Status             39176 non-null  object
 18  Original Language  39176 non-null  object
 19  Budget             39176 non-null  object
 20  Revenue            39176 non-null  object
 21  keyword            20509 non-null  object
 22  Original Title     9372 non-null   object
 23  Writer             21633 non-null  object
 24  Author             511 non-null    object
 25  Story              1963 non-null   object
 26  Teleplay           273 non-null    object
 27  Characters         664 non-null    object
dtypes: float64(1), object(27)
memory usage: 8.4+ MB

In [4]:
for i in range(len(movie)):
    movie['on_streaming_date'][i] = movie['on_streaming_date'][i][:10]
from datetime import datetime
movie['on_streaming_date'] = pd.to_datetime(movie['on_streaming_date'], format='%m/%d/%Y')

C:\Users\ntthu\AppData\Local\Temp\ipykernel_8668\296074416.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['on_streaming_date'][i] = movie['on_streaming_date'][i][:10]

In [5]:
d=movie[movie['on_streaming_date'].dt.year>=2000]
d[(d['Budget']!='-') & (d['Revenue']!='-')].shape

(3816, 28)

In [6]:
df=movie[(movie['Budget']!='-') & (movie['Revenue']!='-')]
df['tagline'] = df['tagline'].fillna('')
df['content'] = df['tagline'] + '\n' + df['overview']
df=df[['url', 'title', 'on_streaming_date', 'genre', 'certification', 'runtime', 'rating', 'content', 'Director',
      'cast1', 'cast1_link', 'cast2', 'cast2_link', 'cast3', 'cast3_link', 'Status', 'Original Language', 'Budget', 'Revenue', 'keyword']]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3816 entries, 9 to 39169
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   url                3816 non-null   object
 1   title              3816 non-null   object
 2   on_streaming_date  3816 non-null   datetime64[ns]
 3   genre              3806 non-null   object
 4   certification      3696 non-null   object
 5   runtime            3781 non-null   object
 6   rating             3816 non-null   float64
 7   content            3816 non-null   object
 8   Director           3808 non-null   object
 9   cast1              3806 non-null   object
 10  cast1_link         3806 non-null   object
 11  cast2              3783 non-null   object
 12  cast2_link         3783 non-null   object
 13  cast3              3758 non-null   object
 14  cast3_link         3758 non-null   object
 15  Status             3816 non-null   object
 16  Original Language  3816 non-null   object
 17  Budget             3816 non-null   object
 18  Revenue            3816 non-null   object
 19  keyword            3624 non-null   object
dtypes: datetime64[ns](1), float64(1), object(18)
memory usage: 626.1+ KB

C:\Users\ntthu\AppData\Local\Temp\ipykernel_8668\3311755170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tagline'] = df['tagline'].fillna('')
C:\Users\ntthu\AppData\Local\Temp\ipykernel_8668\3311755170.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['tagline'] + '\n' + df['overview']

In [7]:
df=df.dropna(axis=0)
df=df.drop_duplicates()
df = df.reset_index(drop=True)
df

,url,title,on_streaming_date,genre,certification,runtime,rating,content,Director,cast1,cast1_link,cast2,cast2_link,cast3,cast3_link,Status,Original Language,Budget,Revenue,keyword
0,https://www.themoviedb.org//movie/10851,Revolver,2005-09-22,"Drama, Thriller, Crime, Mystery",15,1h 51m,64.0,Your mind will not accept a game this big.\nHo...,Guy Ritchie,Jason Statham,https://www.themoviedb.org//person/976-jason-s...,Ray Liotta,https://www.themoviedb.org//person/11477-ray-l...,Vincent Pastore,https://www.themoviedb.org//person/47774-vince...,Released,English,"$27,000,000.00","$7,164,778.00","cash,wrong diagnosis,foretelling,shaky camera ..."
1,https://www.themoviedb.org//movie/10759,The Comebacks,2007-10-19,Comedy,PG-13,1h 47m,49.0,Keep your eye on the ball.\nOut-of-luck coach ...,Tom Brady,Carl Weathers,https://www.themoviedb.org//person/1101-carl-w...,David Koechner,https://www.themoviedb.org//person/28638-david...,Melora Hardin,https://www.themoviedb.org//person/404-melora-...,Released,English,"$15,000,000.00","$13,500,000.00","baseball,baseball bat,sports,coach"
2,https://www.themoviedb.org//movie/78698,Big Miracle,2012-02-10,"Adventure, Drama, Romance",PG,1h 47m,66.0,A family of whales trapped beneath the ice. On...,Ken Kwapis,Drew Barrymore,https://www.themoviedb.org//person/69597-drew-...,John Krasinski,https://www.themoviedb.org//person/17697-john-...,Kristen Bell,https://www.themoviedb.org//person/40462-krist...,Released,English,"$40,000,000.00","$24,719,215.00","whale,based on true story,alaska,reporter,afte..."
3,https://www.themoviedb.org//movie/9275,Death to Smoochy,2002-03-29,"Comedy, Crime, Drama, Thriller",R,1h 49m,59.0,Get ready for an unexpected hit.\nTells the st...,Danny DeVito,Robin Williams,https://www.themoviedb.org//person/2157-robin-...,Edward Norton,https://www.themoviedb.org//person/819-edward-...,Catherine Keener,https://www.themoviedb.org//person/2229-cather...,Released,English,"$55,000,000.00","$8,382,938.00","corruption,success,irish mob,duringcreditsstin..."
4,https://www.themoviedb.org//movie/7350,The Bucket List,2007-12-25,"Drama, Comedy",PG-13,1h 37m,72.0,Find the joy.\nCorporate billionaire Edward Co...,Rob Reiner,Jack Nicholson,https://www.themoviedb.org//person/514-jack-ni...,Morgan Freeman,https://www.themoviedb.org//person/192-morgan-...,Sean Hayes,https://www.themoviedb.org//person/52601-sean-...,Released,English,"$45,000,000.00","$175,372,502.00","africa,himalaya mountain range,brain tumor,par..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3514,https://www.themoviedb.org//movie/339877,Loving Vincent,2017-10-06,"Animation, Drama, Mystery, History",C16,1h 35m,80.0,"The truth is, we cannot speak other than by ou...",DK Welchman,Douglas Booth,https://www.themoviedb.org//person/230680-doug...,Robert Gulaczyk,https://www.themoviedb.org//person/1702761-rob...,Eleanor Tomlinson,https://www.themoviedb.org//person/73357-elean...,Released,English,"$5,500,000.00","$42,187,665.00","painter,artist,letter,investigation,bullying,s..."
3515,https://www.themoviedb.org//movie/280391,Animal Kingdom: Let's Go Ape,2015-04-08,"Adventure, Comedy, Animation",U,1h 40m,53.0,These feet are made for walkin'\nBased on the ...,Jamel Debbouze,Jamel Debbouze,https://www.themoviedb.org//person/2408-jamel-...,Arié Elmaleh,https://www.themoviedb.org//person/82302-arie-...,Mélissa Theuriau,https://www.themoviedb.org//person/1254992-mel...,Released,French,"$37,580,800.00","$16,294,916.00","animal species,evolution,humanity"
3516,https://www.themoviedb.org//movie/71676,Ghost Rider: Spirit of Vengeance,2011-12-10,"Action, Fantasy, Thriller",PG-13,1h 36m,50.0,He rides again.\nWhen the devil resurfaces wit...,Mark Neveldine,Nicolas Cage,https://www.themoviedb.org//person/2963-nicola...,Violante Placido,https://www.themoviedb.org//person/44649-viola...,Ciarán Hinds,https://www.themoviedb.org//person/8785-ciaran...,Released,English,"$57,000,000.00","$132,563,930.00","angel,monk,anti hero,eastern europe,skeleton,p..."
3517,https://www.themoviedb.org//movie/1930,The Amazing Spider-Man,2012-06-29,"Action, Adventure, Fantasy",PG-13,2h 16m,67.0,The untold story begins.\nPeter Parker is an o...,Marc Webb,Andrew Garfield,https://www.themoviedb.org//person/37625-andre...,Emma Stone,https://www.themoviedb.org//person/54693-emma-...,Rhys Ifans,https://www.themoviedb.org//person/7026-rhys-i...,Released,English,"$215,000,000.00","$757,930,663.00","loss of loved one,experiment,vigilante,superhe..."
3518,https://www.themoviedb.org//movie/420634,Terrifier,2018-01-25,"Horror, Thriller",NR,1h 24m,65.0,You Never Forget Your First Kill\nOn Halloween...,Damien Leone,David Howard Thornton,https://www.themoviedb.org//person/1880016-dav...,Jenna Kanell,https://www.themoviedb.org//person/1303873-jen...,Samantha Scaffidi,https://www.themoviedb.org//person/1676771-sam...,Released,English,"$100,000.00","$416,322.00","clown,halloween,gore,slasher,maniac,killer clo..."

In [8]:
for i in range(len(df)):
    df['Budget'][i] = df['Budget'][i][1:]
    df['Revenue'][i] = df['Revenue'][i][1:]

C:\Users\ntthu\AppData\Local\Temp\ipykernel_8668\937159472.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Budget'][i] = df['Budget'][i][1:]
C:\Users\ntthu\AppData\Local\Temp\ipykernel_8668\937159472.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Revenue'][i] = df['Revenue'][i][1:]

In [9]:
from datetime import datetime
df['on_streaming_date'] = pd.to_datetime(df['on_streaming_date'], format='%m/%d/%Y')
df['Budget'] = df['Budget'].str.replace(',', '').astype('float')
df['Revenue'] = df['Revenue'].str.replace(',', '').astype('float')

In [10]:
df = df[df['on_streaming_date'].dt.year>=2000]

In [11]:
def convert_to_minutes(time_string):
    if len(time_string) < 5:
        hours = '0'
        minutes = time_string
    else:
        hours, minutes = time_string.split('h ')
    minutes = minutes[:-1]  # Loại bỏ ký tự 'm' cuối cùng
    total_minutes = int(hours) * 60 + int(minutes)
    return total_minutes
df['runtime'] = df['runtime'].apply(convert_to_minutes)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3519 entries, 0 to 3518
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   url                3519 non-null   object
 1   title              3519 non-null   object
 2   on_streaming_date  3519 non-null   datetime64[ns]
 3   genre              3519 non-null   object
 4   certification      3519 non-null   object
 5   runtime            3519 non-null   int64
 6   rating             3519 non-null   float64
 7   content            3519 non-null   object
 8   Director           3519 non-null   object
 9   cast1              3519 non-null   object
 10  cast1_link         3519 non-null   object
 11  cast2              3519 non-null   object
 12  cast2_link         3519 non-null   object
 13  cast3              3519 non-null   object
 14  cast3_link         3519 non-null   object
 15  Status             3519 non-null   object
 16  Original Language  3519 non-null   object
 17  Budget             3519 non-null   float64
 18  Revenue            3519 non-null   float64
 19  keyword            3519 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(15)
memory usage: 577.3+ KB

In [13]:
df.describe()

           runtime       rating        Budget       Revenue
count  3519.000000  3519.000000  3.519000e+03  3.519000e+03
mean    105.034953    63.982097  3.974342e+07  1.106224e+08
std      22.653410     8.432083  4.871533e+07  2.080399e+08
min       2.000000    19.000000  1.000000e+00  1.000000e+00
25%      94.000000    59.000000  9.000000e+06  6.991232e+06
50%     103.000000    64.000000  2.200000e+07  3.664284e+07
75%     116.000000    69.000000  5.000000e+07  1.154525e+08
max     339.000000   100.000000  4.600000e+08  2.923706e+09

In [14]:
from scipy import stats
z_scores = stats.zscore(df['runtime'])
df = df[(z_scores < 3) & (z_scores > -3)]

In [15]:
df.describe()

           runtime       rating        Budget       Revenue
count  3438.000000  3438.000000  3.438000e+03  3.438000e+03
mean    106.558464    63.767307  3.955899e+07  1.092581e+08
std      16.863447     8.140458  4.799978e+07  2.032384e+08
min      39.000000    19.000000  4.000000e+00  1.000000e+00
25%      94.000000    59.000000  9.000000e+06  7.124196e+06
50%     103.000000    64.000000  2.200000e+07  3.711138e+07
75%     116.000000    69.000000  5.000000e+07  1.153248e+08
max     172.000000   100.000000  3.790000e+08  2.923706e+09

In [16]:
movie_txl = pd.read_csv('Movie_TXL.csv')
movie_txl = movie_txl[['url','Director_link']]
movie_txl

,url,Director_link
0,https://www.themoviedb.org//movie/10851,https://www.themoviedb.org//person/956-guy-rit...
1,https://www.themoviedb.org//movie/10759,https://www.themoviedb.org//person/66512-tom-b...
2,https://www.themoviedb.org//movie/78698,https://www.themoviedb.org//person/29009-ken-k...
3,https://www.themoviedb.org//movie/9275,https://www.themoviedb.org//person/518-danny-d...
4,https://www.themoviedb.org//movie/7350,https://www.themoviedb.org//person/3026-rob-re...
...,...,...
3433,https://www.themoviedb.org//movie/339877,https://www.themoviedb.org//person/1466181-hug...
3434,https://www.themoviedb.org//movie/280391,https://www.themoviedb.org//person/2408-jamel-...
3435,https://www.themoviedb.org//movie/71676,https://www.themoviedb.org//person/20193-mark-...
3436,https://www.themoviedb.org//movie/1930,https://www.themoviedb.org//person/87742-marc-...
3437,https://www.themoviedb.org//movie/420634,https://www.themoviedb.org//person/933176-dami...

In [17]:
df = pd.merge (left = df, left_on = 'url', right = movie_txl, right_on = 'url')
df.columns

Index(['url', 'title', 'on_streaming_date', 'genre', 'certification',
       'runtime', 'rating', 'content', 'Director', 'cast1', 'cast1_link',
       'cast2', 'cast2_link', 'cast3', 'cast3_link', 'Status',
       'Original Language', 'Budget', 'Revenue', 'keyword', 'Director_link'],
      dtype='object')

In [19]:
df = df[['url', 'title', 'on_streaming_date', 'genre', 'certification',
       'runtime', 'rating', 'content', 'Director', 'Director_link', 'cast1', 'cast1_link',
       'cast2', 'cast2_link', 'cast3', 'cast3_link', 'Status',
       'Original Language', 'Budget', 'Revenue', 'keyword']]
df = df.reset_index(drop=True)
df.to_csv('Movie_TXL.csv', index=False)
df

,url,title,on_streaming_date,genre,certification,runtime,rating,content,Director,Director_link,...,cast1_link,cast2,cast2_link,cast3,cast3_link,Status,Original Language,Budget,Revenue,keyword
0,https://www.themoviedb.org//movie/10851,Revolver,2005-09-22,"Drama, Thriller, Crime, Mystery",15,111,64.0,Your mind will not accept a game this big.\nHo...,Guy Ritchie,https://www.themoviedb.org//person/956-guy-rit...,...,https://www.themoviedb.org//person/976-jason-s...,Ray Liotta,https://www.themoviedb.org//person/11477-ray-l...,Vincent Pastore,https://www.themoviedb.org//person/47774-vince...,Released,English,27000000.0,7164778.0,"cash,wrong diagnosis,foretelling,shaky camera ..."
1,https://www.themoviedb.org//movie/10759,The Comebacks,2007-10-19,Comedy,PG-13,107,49.0,Keep your eye on the ball.\nOut-of-luck coach ...,Tom Brady,https://www.themoviedb.org//person/66512-tom-b...,...,https://www.themoviedb.org//person/1101-carl-w...,David Koechner,https://www.themoviedb.org//person/28638-david...,Melora Hardin,https://www.themoviedb.org//person/404-melora-...,Released,English,15000000.0,13500000.0,"baseball,baseball bat,sports,coach"
2,https://www.themoviedb.org//movie/78698,Big Miracle,2012-02-10,"Adventure, Drama, Romance",PG,107,66.0,A family of whales trapped beneath the ice. On...,Ken Kwapis,https://www.themoviedb.org//person/29009-ken-k...,...,https://www.themoviedb.org//person/69597-drew-...,John Krasinski,https://www.themoviedb.org//person/17697-john-...,Kristen Bell,https://www.themoviedb.org//person/40462-krist...,Released,English,40000000.0,24719215.0,"whale,based on true story,alaska,reporter,afte..."
3,https://www.themoviedb.org//movie/9275,Death to Smoochy,2002-03-29,"Comedy, Crime, Drama, Thriller",R,109,59.0,Get ready for an unexpected hit.\nTells the st...,Danny DeVito,https://www.themoviedb.org//person/518-danny-d...,...,https://www.themoviedb.org//person/2157-robin-...,Edward Norton,https://www.themoviedb.org//person/819-edward-...,Catherine Keener,https://www.themoviedb.org//person/2229-cather...,Released,English,55000000.0,8382938.0,"corruption,success,irish mob,duringcreditsstin..."
4,https://www.themoviedb.org//movie/7350,The Bucket List,2007-12-25,"Drama, Comedy",PG-13,97,72.0,Find the joy.\nCorporate billionaire Edward Co...,Rob Reiner,https://www.themoviedb.org//person/3026-rob-re...,...,https://www.themoviedb.org//person/514-jack-ni...,Morgan Freeman,https://www.themoviedb.org//person/192-morgan-...,Sean Hayes,https://www.themoviedb.org//person/52601-sean-...,Released,English,45000000.0,175372502.0,"africa,himalaya mountain range,brain tumor,par..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3433,https://www.themoviedb.org//movie/339877,Loving Vincent,2017-10-06,"Animation, Drama, Mystery, History",C16,95,80.0,"The truth is, we cannot speak other than by ou...",DK Welchman,https://www.themoviedb.org//person/1466181-hug...,...,https://www.themoviedb.org//person/230680-doug...,Robert Gulaczyk,https://www.themoviedb.org//person/1702761-rob...,Eleanor Tomlinson,https://www.themoviedb.org//person/73357-elean...,Released,English,5500000.0,42187665.0,"painter,artist,letter,investigation,bullying,s..."
3434,https://www.themoviedb.org//movie/280391,Animal Kingdom: Let's Go Ape,2015-04-08,"Adventure, Comedy, Animation",U,100,53.0,These feet are made for walkin'\nBased on the ...,Jamel Debbouze,https://www.themoviedb.org//person/2408-jamel-...,...,https://www.themoviedb.org//person/2408-jamel-...,Arié Elmaleh,https://www.themoviedb.org//person/82302-arie-...,Mélissa Theuriau,https://www.themoviedb.org//person/1254992-mel...,Released,French,37580800.0,16294916.0,"animal species,evolution,humanity"
3435,https://www.themoviedb.org//movie/71676,Ghost Rider: Spirit of Vengeance,2011-12-10,"Action, Fantasy, Thriller",PG-13,96,50.0,He rides again.\nWhen the devil resurfaces wit...,Mark Neveldine,https://www.themoviedb.org//person/20193-mark-...,...,https://www.themoviedb.org//person/2963-nicola...,Violante Placido,https://www.themoviedb.org//person/44649-viola...,Ciarán Hinds,https://www.themoviedb.org//person/8785-ciaran...,Released,English,57000000.0,132563930.0,"angel,monk,anti hero,eastern europe,skeleton,p..."
3436,https://www.themoviedb.org//movie/1930,The Amazing Spider-Man,2012-06-29,"Action, Adventure, Fantasy",PG-13,136,67.0,The untold story begins.\nPeter Parker is an o...,Marc Webb,https://www.themoviedb.org//person/87742-marc-...,...,https://www.themoviedb.org//person/37625-andre...,Emma Stone,https://www.themoviedb.org//person/54693-emma-...,Rhys Ifans,https://www.themoviedb.org//person/7026-rhys-i...,Released,English,215000000.0,757930663.0,"loss of loved one,experiment,vigilante,superhe..."
3437,https://www.themoviedb.org//movie/420634,Terrifier,2018-01-25,"Horror, Thriller",NR,84,65.0,You Never Forget Your First Kill\nOn Halloween...,Damien Leone,https://www.themoviedb.org//person/933176-dami...,...,https://www.themoviedb.org//person/1880016-dav...,Jenna Kanell,https://www.themoviedb.org//person/1303873-jen...,Samantha Scaffidi,https://www.themoviedb.org//person/1676771-sam...,Released,English,100000.0,416322.0,"clown,halloween,gore,slasher,maniac,killer clo..."